// ─────────────────────────────────────────────────────────────────────────────
// types.ts — Single source of truth for all planner types
// ─────────────────────────────────────────────────────────────────────────────

export type ExamType = "Internal" | "Board" | "Competitive";

export type SlotType = "standard" | "practice_paper" | "mind_map" | "flashcards";

/**
 * Configured by the student per exam via ExamModal.
 * Stored as JSONB on the exams table (slot_requirements column).
 */
export type SlotRequirement = {
  type: SlotType;
  duration_minutes: number;
  count: number;
  // Only relevant for practice_paper — defines the placement window
  min_days_before?: number;
  max_days_before?: number;
};

export type ExamInput = {
  id: string;
  subject: string | null;
  exam_type: ExamType;
  date: string;
  preparedness: number | null;
  competitive_exam_name?: string | null;
  exam_board?: string | null;
  // Optional — if absent, engine falls back to hardcoded defaults
  slot_requirements?: SlotRequirement[];
};

// ─── Revision engine types ────────────────────────────────────────────────────

/**
 * One logical "demand" per exam per slot type.
 * Standard and practice_paper demands are tracked separately so the engine
 * can place practice papers first (they have stricter placement windows).
 */
export type RevisionDemand = {
  examId: string;
  examDate: string;
  subject: string;
  examType: ExamType;
  preparedness: number;
  slotType: SlotType;
  slotMinutes: number;
  remainingSlots: number;
  // Window constraints — only used for practice_paper
  minDaysBefore: number;
  maxDaysBefore: number;
  // Display metadata
  competitive_exam_name?: string | null;
  exam_board?: string | null;
};

export type PlannedRevisionSlot = {
  date: string;
  examId: string;
  subject: string;
  examType: ExamType;
  slotType: SlotType;
  slotMinutes: number;
  label: string;
  // Practice papers are placed once and never re-generated by nightly sync
  isFixed: boolean;
};

export type DailyRevisionPlan = {
  date: string;
  capacityMinutes: number;
  usedMinutes: number;
  remainingMinutes: number;
  slots: PlannedRevisionSlot[];
};

export type RevisionPlanResult = {
  days: DailyRevisionPlan[];
  demands: RevisionDemand[];
  unmet: RevisionDemand[];
  notes: string[];
};

// ─── Homework scheduler types ─────────────────────────────────────────────────

export type HomeworkTask = {
  id: string;
  name: string;
  estimated_minutes: number;
  due_date: string;
  is_fixed: boolean;
  scheduled_date: string | null;
  status: string;
  subject_name?: string;
  subject?: string;
};

export type PlacedHomeworkTask = HomeworkTask & {
  placedDate: string;
  isBonus: boolean;
  isDone: boolean;
};

export type HomeworkPlacementResult = {
  placedByDate: Record<string, PlacedHomeworkTask[]>;
  tasksToUpdate: { id: string; scheduled_date: string }[];
  occupiedByDate: Record<string, number>;
};

// ─── buildWeekPlan types ──────────────────────────────────────────────────────

export type PlanItem = {
  id: string;
  name: string;
  minutes: number;
  isDone: boolean;
  isBonus: boolean;
  type: "weekly_task" | "deadline_task" | "revision" | "project";
  subject: string;
  // Revision-specific
  slot_type?: SlotType;
  is_fixed?: boolean;
  examId?: string;
  // Homework-specific
  dueDate?: string;
  scheduledDate?: string;
  // Project-specific
  projectId?: string;
};

export type DayPlan = {
  date: string;
  weekly:    { minutes: number; items: PlanItem[] };
  homework:  { minutes: number; actualCompletedMinutes: number; items: PlanItem[] };
  revision:  { minutes: number; items: PlanItem[] };
  projects:  { minutes: number; items: PlanItem[] };
  baseCapacity: number;
  totalPlanned: number;
  totalCompleted: number;
  plannedTaskCount: number;
  completedTaskCount: number;
  spare: number;
};

export type WeekPlan = { days: DayPlan[] };
